### ISSUE TITLE
Change wording of instructions for Proposal title and and Proposal content

### ISSUE THREAD

**Issue by jamesholston** [peer/doc#119]
On new proposal form 
1.  Change "Escolher título"  =>  "Escreva Aqui o Título da Proposta (máximo 100 caracteres)"
-- keep bold and make font as large as possible for available space
2.  Change "Adicionar conteúdo"  =>  "Adicione aqui o texto da proposta"
-- Currently, people complain that they do not readily see this instruction line. Therefore increase font size and make bold

**Comment by mitar** [comment]
I would suggest that for title it is "Write the title of the document here" and "Write the body of the document here".

**Comment by mitar** [comment]
Language should then be:
* "Write the Title of Your Document Here" -> "Escreva Aqui o Título do Seu Documento"
* "Add the text of your document here" -> "Adicione aqui o texto do seu documento"

**Comment by mitar** [comment]
This has been done and merged. Rebuilding images now and then it can be deployed.
