### ISSUE TITLE
Change color of title limit alert

### ISSUE THREAD

**Issue by jamesholston** [peer/doc#127]
White letters on yellow is notorious hard to read.  It is a well-know phenomenon in graphic design.  For consistency and simplicity, I suggest using the same black letters on orange to match the status indicator above.  
-- Insisting on the alert for each character after the suggested limit is very effective.

![screen shot 2018-06-29 at 1 25 57 am](https://user-images.githubusercontent.com/5572598/42073198-6fb40112-7b3b-11e8-9e5f-9337f8fee9ee.png)

**Comment by mitar** [comment]
Status bar comes from AppCivst. In PeerDoc,

I will think what we can do about this.
