### ISSUE TITLE
"Back to document" button (from history view) doesn't always work

### ISSUE THREAD

**Issue by subjective** [peer/doc#164]
I'm using the merge/fork test version for Unifesp.  When I'm in the history view, the "back to document" button doesn't always work.  When I click it, sometimes nothing happens.  Sometimes it works after clicking multiple times.  Sometimes it works after clicking other buttons ("change starts at") and trying the "back to document" button again.

**Comment by mitar** [comment]
True, I have no idea why.

**Comment by mitar** [comment]
In fact the problem is if you click on the text part of the button (label). If outside it works.
