### ISSUE TITLE
Misplaced toolbar buttons after merge

### ISSUE THREAD

**Issue by subjective** [peer/doc#167]
I'm using the merge/fork test version for Unifesp.  After I merge a fork, the editor correctly displays the merged root document.  However, the toolbar buttons seem misplaced:

1.  The toolbar continues to show the "document is fork" blue status button.  If I understand correctly, this should disappear, since the editor is no longer displaying a fork.
2.  The toolbar doesn't show the "fork" button anymore.  But the merged root document should be forkable.

If I refresh the page, I get the correct toolbar: the "document is fork" status button disappears, and the "fork" button appears.

**Comment by mitar** [comment]
So are you talking here about this being embedded or standalone?

I think you are confused which document you are seeing. How are you sure you are seeing the correct one?

**Comment by subjective** [comment]
I'm doing everything in the version that is embedded on AppCivist.  But I was using the buttons on the PeerDoc embed, not the buttons on AppCivist.  I was expecting that PeerDoc would show me the root document after the merge was accepted.  But I suppose I'm seeing the fork document, and I can return to the root document by clicking "Mother Document" on AppCivist.  So I'll close the issue.

**Comment by mitar** [comment]
You should not use the buttons in PeerDoc. They are there only for debugging purposes.

**Comment by mitar** [comment]
So after merging, I think you should stay on the fork. And what I see is that you get "merged" and "fork" labels, and "Fork" button is available.

So you should try to fork and merge and observe if buttons are reasonable. So your description above is strange. if you stayed on the fork, then you should still have "Fork" button available.

**Comment by mitar** [comment]
(But I cannot reproduce that.)

**Comment by subjective** [comment]
On [this proposal](https://testpb.appcivist.org/#/v2/assembly/113/campaign/215/group/296/contribution/5773), there is no "Fork" button.  (The buttons are in Portuguese even when AppCivist is in English.)

![peerdoc-bug-3](https://user-images.githubusercontent.com/5214824/48952635-de20b200-ef10-11e8-9041-85ae0aba5e44.png)

If I try to fork through the button on AppCivist ("Create Amendment"), I get an error on AppCivist.  It's the same error I had reported [here](https://github.com/peer/doc/issues/166#issuecomment-440938830).

**Comment by mitar** [comment]
> The buttons are in Portuguese even when AppCivist is in English.

No, the buttons display the translation ID string when there is no translation, and there is no translation yet for these buttons.

> On this proposal, there is no "Fork" button.

Yes, merged amendments cannot be forked. This is on purpose. What would be an amendment to an accepted amendment? If you want to do that, just fork the original document which already includes the accepted amendment?

**Comment by subjective** [comment]
> No, the buttons display the translation ID string when there is no translation, and there is no translation yet for these buttons.

I know that, but I was mentioning a different thing: the embedded PeerDoc is always in Portuguese even when AppCivist is set to English.  So regardless of the AppCivist language I always see Portuguese strings on PeerDoc (and yes, some English ID strings when there is no translation available).  But this is probably an AppCivist issue and doesn't matter for Unifesp anyway.

> Yes, merged amendments cannot be forked. This is on purpose. What would be an amendment to an accepted amendment? If you want to do that, just fork the original document which already includes the accepted amendment?

That makes sense!  So let's just remove the button from AppCivist, rather than add it to PeerDoc.  (I see you reported it on the AppCivist Slack already!)

**Comment by mitar** [comment]
> I know that, but I was mentioning a different thing: the embedded PeerDoc is always in Portuguese even when AppCivist is set to English.

If I remember correctly, you have to change language in your settings, not in the drop-down menu, and then it works.

**Comment by mitar** [comment]
Feel free to report the language issue to AppCivist. So PeerDoc has support for multiple languages and AppCivist has to pass it correctly through its embed API. I think the problem is in the latter.
