### ISSUE TITLE
Make sure undo/redo works accross sessions

### ISSUE THREAD

**Issue by mitar** [peer/doc#3]
* Inside one session it should undo/redo only changes by the user.
* For changes before this session, it should undo/redo all changes.

**Comment by voluntadpear** [comment]
Checked that each user changes are isolated when applying undo/redo. But, if you close a current session and open the same document at another time, you can't undo between the previous states, you can only undo/redo your current changes.

**Comment by mitar** [comment]
I think this is probably OK. For undo/redo between sessions you could use in the future the history tab and revert to a particular older version.

**Comment by mitar** [comment]
Thanks for looking into this.
