### ISSUE TITLE
Add support for translation of all user-visible strings

### ISSUE THREAD

**Issue by mitar** [peer/doc#32]
* Decide which library to use:
  * [vue-ii18n](https://github.com/kazupon/vue-i18n) seems to be popular.
    * My main issue is that the pluralization support seems to be limited: https://github.com/kazupon/vue-i18n/issues/284
    * And I am not sure how widely their storage format for messages (it looks like JSON) is supported by various UI apps translators might be using to translate.'
  * [vue-gettext](https://github.com/Polyconseil/vue-gettext)
    * Uses standard gettext which means we can use many tools from the ecosystem.
    * But there are some known limitations in [extracting strings](https://github.com/Polyconseil/vue-gettext#known-issues).
    * There is an [alternative extractor available though](https://github.com/GUI/gettext-vue).
* Extract all user-visible strings into a table and make an EN-US translation from current strings.

**Comment by voluntadpear** [comment]
Based on these two options I think **vue-gettext** is worth the try and see if the alternative extractor is able to handle our **.vue** files. Using standard **gettext** seems nice.

If it's troublesome working with **vue-gettext** we can try **vue-ii18n** and use the custom pluralizations techniques they describe here https://github.com/kazupon/vue-i18n/issues/78. But as you say, we should find is there's any UI tool for translators to work with those JSON files.

**Comment by mitar** [comment]
Yes, lets try getttext. Can you try?

**Comment by voluntadpear** [comment]
Yeah, I'll work on that!

**Comment by mitar** [comment]
One reason to use gettext is also that then we can use [this interface](https://weblate.org/en/) for user interface for translators.

**Comment by rodneyrehm** [comment]
@mitar weblate is no reason to use gettext. we use weblate with the (nested) [json format](https://docs.weblate.org/en/latest/formats.html#json-files) and vue-i18n just fine. (however there are no flags and comments as you'd have in a PO file…)

**Comment by mitar** [comment]
Is there any downside of using PO files?

**Comment by rodneyrehm** [comment]
> Is there any downside of using PO files?

well, either you parse them in the browser and have to ship the parser to the client, or you convert to JSON at build time. The question really is what PO can do that JSON cannot (comments, flags like "fuzzy", …) and if you really need any of that. Otherwise it's just a pointless in-between format.

**Comment by mitar** [comment]
To me it has support for complicated plurals. Which it seems vue-i18n does not support?

**Comment by rodneyrehm** [comment]
> To me it has support for complicated plurals.

We use [intl-messageformat](https://www.npmjs.com/package/intl-messageformat) to cover that (and more) in a single message. That format [was](https://github.com/tc39/ecma402/issues/92) considered for addition to [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl). We'd been using [ICU MessageFormat](http://userguide.icu-project.org/formatparse/messages) in other projects before switching to Vue, so looking at different approaches didn't make sense for us at the time. It works fine for us, not sure if it will be the same for you, though. (Unfortunately weblate does not support ICU MessageFormat in any useful way in the UI)

**Comment by mitar** [comment]
Done with #34.

For now we are going with `.po`. We can reinvestigate this in the future.

**Comment by mitar** [comment]
Interesting approach might be using Mozilla [Fluent](http://projectfluent.org/) and their [Pontoon](https://pontoon.mozilla.org) UI.
