### ISSUE TITLE
Integration with AppCivist

### ISSUE THREAD

**Issue by mitar** [peer/doc#38]
One use of PeerDoc is to embed it into AppCivist as an editor. So we should make PeerDoc embeddable.  The following is how we will make this work:

* When AppCivist will embed PeerDoc, it will use an embedding URL in the following form:
  * `https://peerdoc.org/document/<documentId>?embed=true&user=<base64 encrypted user payload>`
* To create a new document, AppCivist will create a POST HTTP request to `https://peerdoc.org/document?user=<base64 encrypted user payload>`. PeerDoc will respond by creating a document with that user as an author and return a JSON with:
  * `path`: `/document/<documentId>`
  * `documentId`: `<documentId>`
  * `status`: `success` or `error`
  * AppCivist should record this path (or documentId) and use it as base for the embedding URL.
  * So document creation is server-side only and is not visible to the user.
* The embedding URL is parsed both on the client and server side.
  * On the client side, if URL contains `embed=true`:
    * Web app header/menu/top toolbar is not shown.
    * Web app sends a message to parent window using [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) call with initial size of the content of the web app and after every size change:
      * `targetWindow` = `window.parent`
      * `message` = `{size: {width: ..., height: ...}}`
      * `targetOrigin` = `'*'`
      * Maybe we can use a library, I have found: https://github.com/davidjbradshaw/iframe-resizer
  * If URL contains  `user` query string argument, client-side sends the value through a Meteor method call to the server-side to sign the user in.
  * The `user` value is an AES-GCM encrypted message with 128 bit shared key between AppCivist and PeerDoc. The message contains:
    * 12 bytes of the message IV
    * 16 bytes of the AES-GCM authentication tag
    * the rest is cipher text
  * The cipher text is encrypted serialized JSON UTF8 encoded and contains the following keys:
    * `nonce`: 22 character nonce string. This nonce is stored into a special collection in PeerDoc (named `appcivist.nonces`). They have to be unique (unique index on them). Each nonce can be stored only once. Before message is processed, nonce is added to the collection. Only if nonce is added successfully the message is processed. If nonce is not added, message is not processed so any user which is logged in currently stays logged in.
    * `avatar`: URL to an avatar image.
    * `username`: Username.
    * `email`: E-mail address.
    * `id`: AppCivist internal user ID (for future needs).
* Base64 encoding uses [`-` and `_`, and `.` for padding](https://en.wikipedia.org/wiki/Base64#URL_applications).
* When being embedded, button for making a draft published is not shown (we will manually published them after the end of the drafting phase).
* Every time an embedding URL is used, a new encrypted user payload has to be made.
* Any links inside the embedded iframe should load in the whole window, not just inside the iframe.

The proposed order of requests for a new document is:
* AppCivist makes server-to-server HTTP POST request to create a new document with `user` query string argument.
* It receives the URL of the created document back, it extracts `documentId` from it and stores it.
* It renders an iframe with embedding URL.
* User loads embedding URL inside the iframe, PeerDoc loads.
* PeerDoc sends a message to parent window about its iframe size and AppCivist resizes the iframe.
* At the same time, because of the `user` query string argument and, through a Meteor method call, app signs the user in for the connection. This should update the client as well after user is signed in.
* When AppCivist wants to make document published and freeze it, it makes server-to-server HTTP POST request to publish it.

Logging the AppCivist user should be implemented as a special Meteor accounts service. The idea is that the user will then have the following entry in its `services` field in its document in `users` collection:

```
{
  "username": "...",
  "emails" : [
    {
      "address" : "...",
      "verified" : true
    }
  ],
  "services": {
    "usertoken" : {
      "id" : "...",
      "username": "...",
      "email" : "...",
      "avatar" : "...",
    }
  }
}
```

Both `username` and `emails.address` should be automatically set as well to those from AppCivist.

See also: #36

**Comment by mitar** [comment]
I looked how JWT would help us here, but I do not think it is necessary. AES-GCM should be enough. We do not need customization here. This is just a temporary approach anyway. In the future we will move to OAuth.

**Comment by mitar** [comment]
I made https://github.com/peer/doc/tree/user-token branch. It has a base how you can login using user token. The call has to start from the client and you pass the token to the server using a Meteor method, and then that one should proceed as described above.

**Comment by voluntadpear** [comment]
Should we use a JS library to decrypt the AES-GCM key? I found [aes-js](https://github.com/ricmoo/aes-js) and seems to support many modes of operation, but it seems it doesn't supports *GCM* mode of operation.

I've also found [aes4js](https://github.com/rndme/aes4js) and [node-aes-gcm](https://github.com/xorbit/node-aes-gcm). But, they are less popular.

What do you think @mitar?

**Comment by mitar** [comment]
Decryption of that happens only on the server side. So just use [node crypto](https://nodejs.org/api/crypto.html) module. It uses OpenSSL. There are some examples how to do this: https://gist.github.com/rjz/15baffeab434b8125ca4d783f4116d81

**Comment by mitar** [comment]
I will update the spec above for the message to be "IV | auth tag | ciphertext" because it seems this is how node prefers it.

**Comment by voluntadpear** [comment]
Perfect

**Comment by mitar** [comment]
I will update also the initial description with new information how authentication happens. Now the client has to send a message to the server.

**Comment by mitar** [comment]
I also renamed the service to `usertoken`. So that it is more general.

**Comment by mitar** [comment]
See https://github.com/peer/doc/commit/95444b53250efdbd5a4256ff039bd1e3ce8e9b3d for example implementation.

**Comment by mitar** [comment]
I think that populating `services` might be possible to be done through some existing Meteor accounts API. Similarly to how we are using it to login the user.

**Comment by mitar** [comment]
A code example to encode and decode user token:

```js
import crypto from 'crypto';

const baseFromMap = {
  '+': '-',
  '/': '_',
  '=': '.',
};

const baseToMap = {
  '-': '+',
  '_': '/',
  '.': '=',
};

const keyHex = crypto.randomBytes(16).toString('hex');

const data = {avatar, username, id, email};

function encrypt(data, keyHex) {
  data.nonce = '...';
  const json = JSON.stringify(data);
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-128-gcm', new Buffer(keyHex, 'hex'), iv);
  const buffers = [];
  buffers.push(cipher.update(json, 'utf8'));
  buffers.push(cipher.final());
  return Buffer.concat([iv, cipher.getAuthTag()].concat(buffers)).toString('base64').replace(/[\+\/=]/g, (c) => baseFromMap[c]);
}

function decrypt(tokenBase, keyHex) {
  const token = new Buffer(tokenBase.replace(/[-_\.]/g, (c) => baseToMap[c]), 'base64');
  const iv = token.slice(0, 12);
  const authTag = token.slice(12, 28);
  const ciphertext = token.slice(28);
  const decipher = crypto.createDecipheriv('aes-128-gcm', new Buffer(keyHex, 'hex'), iv);
  decipher.setAuthTag(authTag);
  const json = Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf8');
  return JSON.parse(json);
}
```

**Comment by mitar** [comment]
This is how I test iframe resizing:

```
<html>
  <body>
    <p>Before.</p>
    <iframe src="http://localhost:3000/document/kZuiP9q3oKzZdCaya?embed=true" style="width: 100%; border: 0;" frameborder="0" scrolling="no"></iframe>
    <p>After.</p>
    <script>
      window.addEventListener('message', function (event) {
        if (event.data.size) {
          Array.prototype.forEach.call(document.getElementsByTagName('iframe'), function (element) {
            if (element.contentWindow === event.source) {
              element.style.height = `${event.data.size.height}px`;
            }
          });
        }
      }, false);
    </script>
  </body>
</html>
```

**Comment by mitar** [comment]
I will close this now and open individual issues for future changes.

> Hiding publish button when embedding.

This will be done through permissions which you will be able to configure on instance being embedded.
