### ISSUE TITLE
Title of published document not displayed in Documents list

### ISSUE THREAD

**Issue by jamesholston** [peer/doc#55]
Title of published document not displayed in Documents.  

The "Untitled published 3 minutes ago" in the screen shot has the title:  JH Test Document 1.  But that title doesn't display in the list.

![screen shot 2018-03-31 at 4 06 07 pm](https://user-images.githubusercontent.com/5572598/38166642-889d1468-34fd-11e8-8216-5c9776a779ab.png)
 list

**Comment by mitar** [comment]
Fixed.
