### ISSUE TITLE
Prosemirror not loading 

### ISSUE THREAD

**Issue by maxscience** [peer/doc#72]
Checked about this with @mitar 
It looks like a logic error about user login? Same issue with both Safari and Firefox.
Meteor console doesn't show errors.

1. did a clean install following the readme
2. clicked sign in and used username 'test'
3. clicked on documents and created a new document
4. editor doesn't show up on the main page (screenshot)
5. if I click again on Sign in, page shows 'access denied'
![schermata 2018-04-18 alle 20 31 32](https://user-images.githubusercontent.com/2937441/38953328-b0af4b6a-434e-11e8-80bd-283666028279.png)

**Comment by mitar** [comment]
You didn't clone the repository recursively. See README for instructions.
